### ISSUE TITLE
S 4.0: sort-selector partial not updated to match core changes

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-themes/foundation#50]
The sort-selector.phtml in the core changed a little in S 4.0, but Foundation has a custom one that isn't updated for those changes. What actual changes did Foundation need to make here? Could we drop the override possibly?

Relatedly, core views now use the browse() helper to provide the default sort options rather than having them written into the theme view, so we might as well update to have that as well (doing this doesn't affect what's needed for sort-selector.phtml though).

**Comment by kimisgold** [comment]
Fixed in v1.3.3
