### ISSUE TITLE
Media list thumbnails getting compressed

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/foundation#51]
In 4.0, the media list doesn't play well with long media titles:

![foundation-thumbnail2](https://user-images.githubusercontent.com/28012148/217356709-d158e310-5f74-4fec-8771-fe678eebe0ee.PNG)

Probably need an overflow:hidden on the media title, and/or should modify the flex so that the thumbnails don't get squished. 

This will likely come up in other themes when they support customized resource page regions and media lists get put into small columns.

**Comment by zerocrates** [comment]
We probably do want to maintain showing the full title... there's probably just a little flexbox adjustment to be done here to tell it we don't want to allow the image to shrink.

**Comment by kimisgold** [comment]
A fix is ready to pull and test @allanaaa .

**Comment by kimisgold** [comment]
My preference has been to vertically center. Glad the thumbnails are sizing correctly now.
