### ISSUE TITLE
v1.3.3 - Header menus display below the lightGallery media (was #48)

### ISSUE THREAD

**Issue by ManOnDaMoon** [omeka-s-themes/foundation#54]
Hello @kimisgold 

I'd like to reopen #48 as the issue is still present in v1.3.3

The `z-index: 2;` applied on `.is-submenu` displays the menu above the LightGallery background now, but still below the pictures themselves, and the sub-menu hover events are not triggered either.

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/3284234/219157468-6c25e12d-8a7b-4477-93c3-f4e01284fa34.png">

From my own tests, `z-index: 3;` seems to be the magic number here, even if I dont grasp the logic behind it.

**Comment by zerocrates** [comment]
The other way around for this kind of problem is typically to set a z-index on what should be on the bottom, so the container for the gallery in this case.

If you set for example `position: relative; z-index: 0;` on the gallery container, everything within it will be treated as having a zero z-index (but things inside the gallery will still stack correctly relative to each other).

**Comment by kimisgold** [comment]
@katknow Could you test the fixes for this? Especially on desktop browsers, test that flyout menus appear above all lightgallery media.

**Comment by katknow** [comment]
@kimisgold this seems to work properly now! Tested on desktop in Chrome, Edge, and Firefox across multiple media types.
