### ISSUE TITLE
Multi-value fields display issue in Omeka 4.0.1 with Foundation 1.3.3

### ISSUE THREAD

**Issue by jbhistorian** [omeka-s-themes/foundation#56]
I upgraded one of my websites to Omeka S 4.0.1 today (I was previously on version 3.2). I also upgraded the Foundation theme to version 1.3.3 at the same time.

There is an issue with displaying metadata fields that have multiple values. It's like they are all trying to squish together on the same line instead of each value displaying on a separate line. Please see screenshots below for a comparison of old vs. new site version.

In Theme Settings, "Metadata Layout for Show Pages" is set to "Inline" as it was previously.
When I change this setting to "Stack," this problem goes away. However, I would still prefer to use the "Inline" option if this problem can be fixed.

**Old:**

![image](https://user-images.githubusercontent.com/89092402/222052733-9a6d4777-c7a6-408f-9c59-d3c0b5b49054.png)
-----
**Compare with new:**

![image](https://user-images.githubusercontent.com/89092402/222052754-ae394595-f979-424a-a8cc-c2208d0e8b24.png)-----

**Old:**

![image](https://user-images.githubusercontent.com/89092402/222052775-c28e7ed7-11d0-441e-ab51-3ffa859f2aa8.png)-----

**Compare with new:**

![image](https://user-images.githubusercontent.com/89092402/222052786-c633bde7-f8a8-4e5e-af01-86c3cd68a7af.png)

---

**Comment by kimisgold** [comment]
Thanks for this. We've made a fix in https://github.com/omeka-s-themes/foundation/commit/8b6260b879f2e3e869804a9bd83e4a927578a4e2 that should be out soon in the next release.

**Comment by zerocrates** [comment]
The fix for this was released with version 1.3.4.
