### ISSUE TITLE
Omeka resources as values layout issue

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/foundation#58]
When a resource is set as a value, something similar to #56 is happening - values are displaying with some kind of unwanted word-wrap/inline issue.

![resource-as-value](https://user-images.githubusercontent.com/28012148/228016093-982e1617-78e9-4db6-8ac1-96ad8696e8ba.PNG)

![resource-as-value2](https://user-images.githubusercontent.com/28012148/228016099-2c175a58-fc6c-4cb0-9154-9b0329151b8a.PNG)

**Comment by kimisgold** [comment]
Gotcha, looks like it was an oversight in the stacked metadata mode. A fix is ready: can you test in both stacked and inline mode?

**Comment by allanaaa** [comment]
I'm not sure what you mean by inline and stacked. Is that a setting under another name? Either way, it looks good now.

**Comment by kimisgold** [comment]
Yes sorry: it's this theme setting, "Metadata layout for show pages".

![image](https://user-images.githubusercontent.com/606764/228047791-2ad7af31-96c8-44ad-b2d0-2a4396f04aaa.png)
