### ISSUE TITLE
Test new block templates

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/foundation#63]
The Omeka S 4.1 release candidate introduces the block templates feature, which allows theme developers to provide their users with alternative versions of page blocks. Foundation has introduced the following templates for each block:

* Asset
  * **Card**: Uses [Foundation Framework's card container](https://get.foundation/sites/docs/card.html) styles.
  * **Media object**: Uses [Foundation Framework's media object container](https://get.foundation/sites/docs/media-object.html) styles.
* Browse preview
  * **List**: Ignores theme setting for browse view layouts and displays all resources as a single column list.
  * **Grid**: Ignores theme setting for browse view layouts and displays all resources in a grid that maxes out at 4 columns.
  * **Toggle (default: list)**: Ignores theme setting for browse view layouts and lets the user choose their browse style, defaulting to a single column list of resources.
  * **Toggle (default: grid)**: Ignores theme setting for browse view layouts and lets the user choose their browse style, defaulting to a grid of resources maxing out at 4 columns.
* Item with metadata
  * **Large media left**: A 2-column layout with the item media rendered to the left of the metadata.
  * **Large media right**: A 2-column layout with the item media rendered to the right of the metadata.
* List of pages
  * **With container**: Provides a gray box container.
* List of sites
  * **Card**: Uses [Foundation Framework's card container](https://get.foundation/sites/docs/card.html) styles for each site.
* Page title
  * **Accent**: Renders the page title with the theme's primary color as a background color.

These changes are all on the `master` branch. Test that these blocks work as expected and scale well at narrower browser widths. I'm also open to suggestions for other kinds of block templates.

**Comment by katknow** [comment]
I can't get the alignment to change in the Asset block. No matter what it stays the same. (Although after testing all I'm wondering if I don't understand alignment--nothing seems to change on any of them so I'm wondering if it might be user error)

For the Browse Preview, the Heading remains when checked for the Default, but if you change it to any other view the Heading disappears even when the box is checked. 

In Item with Metadata, I get the below error when I try to use the "Large Media Right" Template:

> >  Laminas\View\Exception\RuntimeException
> Laminas\View\Renderer\PhpRenderer::render: Unable to render template "common/block-template/large-media.phtml"; resolver could not resolve to a file
> 
> Details:
> 
> Laminas\View\Exception\RuntimeException: Laminas\View\Renderer\PhpRenderer::render: Unable to render template "common/block-template/large-media.phtml"; resolver could not resolve to a file in /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php:497
> Stack trace:
> #0 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Helper/Partial.php(61): Laminas\View\Renderer\PhpRenderer->render(NULL, NULL)
> #1 [internal function]: Laminas\View\Helper\Partial->__invoke('common/block-te...', Array)
> #2 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(396): call_user_func_array(Object(Laminas\View\Helper\Partial), Array)
> #3 /var/www/html/katknow/OmekaSTesting/themes/Foundation/view/common/block-template/iwm-large-media-right.phtml(4): Laminas\View\Renderer\PhpRenderer->__call('partial', Array)
> #4 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/var/www/html/k...')
> #5 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Helper/Partial.php(61): Laminas\View\Renderer\PhpRenderer->render(NULL, NULL)
> #6 [internal function]: Laminas\View\Helper\Partial->__invoke('common/block-te...', Array)
> #7 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(396): call_user_func_array(Object(Laminas\View\Helper\Partial), Array)
> #8 /var/www/html/katknow/OmekaSTesting/application/src/Site/BlockLayout/ItemWithMetadata.php(31): Laminas\View\Renderer\PhpRenderer->__call('partial', Array)
> #9 /var/www/html/katknow/OmekaSTesting/application/src/View/Helper/BlockLayout.php(253): Omeka\Site\BlockLayout\ItemWithMetadata->render(Object(Laminas\View\Renderer\PhpRenderer), Object(Omeka\Api\Representation\SitePageBlockRepresentation), 'common/block-te...')
> #10 /var/www/html/katknow/OmekaSTesting/application/src/View/Helper/PageLayout.php(78): Omeka\View\Helper\BlockLayout->render(Object(Omeka\Api\Representation\SitePageBlockRepresentation))
> #11 /var/www/html/katknow/OmekaSTesting/application/view/omeka/site/page/content.phtml(1): Omeka\View\Helper\PageLayout->render(Object(Omeka\Api\Representation\SitePageRepresentation))
> #12 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/var/www/html/k...')
> #13 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
> #14 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
> #15 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
> #16 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
> #17 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
> #18 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
> #19 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
> #20 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
> #21 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
> #22 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
> #23 /var/www/html/katknow/OmekaSTesting/index.php(21): Laminas\Mvc\Application->run()
> #24 {main}

List of Pages worked fine.

List of Sites also works, but I wonder if there should be a little more explanatory text connecting the max number of sites and pagination, although this could be explained a bit more in depth in documentation.

Page Title works well. I really like the Accent option.

**Comment by kimisgold** [comment]
Thanks, there are some great catches here. I'll get on addressing this feedback.

**Comment by zerocrates** [comment]
On alignments: that's probably a bug we've fixed. Are you looking at this on the 4.1rc tag? Latest develop should fix it.

**Comment by kimisgold** [comment]
> In Item with Metadata, I get the below error when I try to use the "Large Media Right" Template...

This is fixed and ready for another look.

> For the Browse Preview, the Heading remains when checked for the Default, but if you change it to any other view the Heading disappears even when the box is checked.

I tried recreating this locally and on your test site but couldn't find it. Could you outline exact steps to recreate this bug?

**Comment by katknow** [comment]
The Item with Metadata is looking good now!

For Browse Preview, I think I accidentally mixed up my terms. It's actually the "Preview title" that is not appearing, which I'm guessing is independent of the check box. It is not appearing for anything other than default. Sorry about that, I read heading in the description and that's the word my brain latched on to.

**Comment by kimisgold** [comment]
Thanks for the clarification. Both the custom preview title and link text weren't getting included in the block templates, but that should now be fixed in https://github.com/omeka-s-themes/foundation/commit/c43bb81b350b166bb1b051c2c7d2eec0d7c9f4ab.

**Comment by kimisgold** [comment]
The CSRF error typically happens when you've had the form open too long without submitting.

I just checked your theme in the dev server and it looks like what you have is not up to date? I added some unrelated commits this morning, but let's see if we can get those in along with the browse preview fixes.

**Comment by katknow** [comment]
Pulled again and it seems to be working fine, must've done something wrong earlier.

**Comment by allanaaa** [comment]
The Asset block using the card template is a bit funky: with no link set, it just shows as a full-width page block. With a page link appearing, it looks like this:

<img width="972" alt="Screenshot 2024-03-18 at 14 20 06" src="https://github.com/omeka-s-themes/foundation/assets/28012148/db047737-a73c-4a6b-85a9-7dcac1b247a9">

The width of the asset is being shrunk (and the total height of the block) in an unexpected way. 

Note that the link is still the full width and highlights on mouseover:

<img width="973" alt="Screenshot 2024-03-18 at 14 20 15" src="https://github.com/omeka-s-themes/foundation/assets/28012148/4f4f4132-a3a8-440a-8752-54ae1e45610b">

**Comment by allanaaa** [comment]
Here's my understanding of the Foundation page templates, as will go in the docs. Let me know if there are any problems with this:

* Default: Constrain the page content to a width of 1200 pixels, if the navigation is set to "horizontal dropdown" rather than "full height column". 
* Full-width: Occupy all available width in the browser window, minus the navigation column. Page subnavigation will appear above page content rather than beside it.

For block templates I just copied your theme docs. I'll screengrab one or two for examples. It's gonna live here, where Foundation already has its own section:

https://omeka.org/s/docs/user-manual/sites/site_theme/#foundation-theme-settings

**Comment by kimisgold** [comment]
@allanaaa That looks good, though I would specify "minus the vertical navigation column if using" or something to that effect. I think the horizontal navigation is the theme default.

**Comment by allanaaa** [comment]
Okay, I think this one is ready to be closed?
