### ISSUE TITLE
Foundation 4.1 display issues

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/foundation#65]
In Foundation:

1. The latest version of the Item Carousel Block is picking up button colours in its arrow buttons:

<img width="1200" alt="Screenshot 2024-02-27 at 12 05 18" src="https://github.com/omeka-s-themes/foundation/assets/28012148/6dbd09bb-9f9e-44a8-becb-4eee9f5a58c7">

2. Thumbnail images have a margin-left that shouldn't be there (or at least shouldn't be inside the borders):

<img width="1220" alt="Screenshot 2024-02-27 at 12 05 50" src="https://github.com/omeka-s-themes/foundation/assets/28012148/cfde9fbc-6a11-46f7-9a28-34a42036610c">

```
.resource-list .resource img {
  float: right;
  margin-left: 1rem;
}
```

3. The Table of Contents block has links inside it that are set to `display:block` so they aren't appearing next to their list indenters:

<img width="478" alt="Screenshot 2024-02-27 at 12 12 49" src="https://github.com/omeka-s-themes/foundation/assets/28012148/8e058322-c06b-479f-bc0c-c365be05e887">

This is coming from `.menu a, .toc-block > ul a, .toc-block ul ul a, ...` in the CSS.

**Comment by allanaaa** [comment]
4. The List of sites page block has distorted dimensions for the thumbnails. Maybe they can just be set to `cover` so they maintain their original ratios and get cropped as needed. 

<img width="385" alt="Screenshot 2024-02-27 at 13 04 05" src="https://github.com/omeka-s-themes/foundation/assets/28012148/3d47dd4e-c470-4a7e-b61f-62aded807634">

The code in `seafoam.css` is
.list-of-sites .site-list .media-object-section .site-thumbnail-image, .list-of-sites .site-list .card .site-thumbnail-image {
  width: 100%;
  max-width: none;
}

and the code in `page-blocks.css` is 
.list-of-sites .site-list .site-thumbnail-image {
  max-height: 72px;
  float: left;
  margin-right: 1rem;
}

**Comment by kimisgold** [comment]
Fixes for each of these 4 items have been pushed and are ready for a look.

**Comment by allanaaa** [comment]
Weirdly, I'm still getting that margin-left on some Browse Preview images, but not all. 

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/page/my-12-column-grid-page

<img width="591" alt="Screenshot 2024-02-29 at 11 03 12" src="https://github.com/omeka-s-themes/foundation/assets/28012148/550b2887-058f-4cb8-b1c4-a99e64fd9e1e">

Just the one image on that page. 

All the images on this page: http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/page/my-grid-page

But none on this page: http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/page/my-11-column-grid-page

**Comment by kimisgold** [comment]
I think I figured it out: there was an inconsistent class on the image wrapper in the default custom browse preview. That should now be corrected in https://github.com/omeka-s-themes/foundation/commit/ea49d2942f5049ae3669f939cdeee72067f5aead.
