### ISSUE TITLE
Banner inconsistency

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/foundation#66]
In Inkwell, my site banner is set to "within content" and that's working on most pages:

<img width="1199" alt="Screenshot 2024-03-18 at 16 00 08" src="https://github.com/omeka-s-themes/foundation/assets/28012148/a818823f-37ae-4785-b654-8eb19fbb20ec">

But on some pages it's not:

<img width="1211" alt="Screenshot 2024-03-18 at 16 00 16" src="https://github.com/omeka-s-themes/foundation/assets/28012148/848af046-3539-4c21-a594-647dc75cfac1">

And I can't figure out what's different. Both of the containers are the same width and both divs say "banner contained" as classes.

**Comment by kimisgold** [comment]
I'm having trouble recreating this. Could you provide a live link to look at?

**Comment by kimisgold** [comment]
There are some flex shenanigans involved in making the vertical menu work, and it was causing the banner to grow when the content area is small. I think it should be fixed now.
