### ISSUE TITLE
Linked resources display issue in right sidebar region

### ISSUE THREAD

**Issue by jbhistorian** [omeka-s-themes/foundation#68]
I am attempting to put the Linked Resources block into the Right Sidebar region on an Item Page.

However, there is an overlap that occurs between the filter dropdown menu and the page number box. This overlap happens even when using a wide screen:

<img width="1352" alt="image" src="https://github.com/omeka-s-themes/foundation/assets/89092402/a298fc56-5f7e-4ec6-84a4-72d190abf970">

Perhaps the pagination can be stacked above or below the filter, rather than side by side, to avoid this problem?

**Comment by kimisgold** [comment]
Thank you for reporting this. I've implemented some wrapping and other layout changes that should resolve this issue. You can see these changes in the latest release, v1.4.0.
