### ISSUE TITLE
Test new resource page blocks

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/foundation#71]
Foundation now provides three new configurable blocks for resource show views: **custom callout**, **custom callout with frame**, and **tab navigation**. 

**Custom Callout (with Frame)**

The user can provide some kind of fixed html content to appear on every resource page. The content is populated in the "Custom Callout" theme setting. There is the original unadorned version, and then the version with a frame using the stylesheet's default container styles.

Regular custom callout block: 
<img width="600" alt="Item show page with custom callout content in a right sidebar alongside item metadata." src="https://github.com/user-attachments/assets/f6f070a1-64ac-49c7-b9f3-99a9637df73a">

Custom callout with frame block:
<img width="600" alt="Item show page with framed custom callout content in a right sidebar alongside item metadata." src="https://github.com/user-attachments/assets/17c1e079-6105-4d42-97be-a9d424c912c4">

**Tab Navigation**

This is a subnavigation element that controls visibility of content sections. It makes large amounts of content less unwieldy and allow each section to have individual focus. By default, it controls content blocks that appear in the "Main with sidebar" region, and displays in a vertical layout. The theme setting "Tab Navigation Content Area for Show Pages" allows users to choose between "Main with sidebar" and "Full-width main" as the regions targeted by the tab navigation. The theme setting "Tab Navigation Layout for Show Pages" controls whether the tabs appear in a vertical or horizontal layout.

Tabs can appear in any region. If they are used in the "Main with sidebar" or "Full-width main" regions, they will always appear above all other content. In sidebar regions, their order is configurable. They should be screen-reader friendly and keyboard accessible.

Sample configurations:
<img src="https://github.com/user-attachments/assets/eae4727b-ae8f-4953-8f2d-82f853481e54" width="600" alt="Tab navigation configured in the left sidebar.">

<img src="https://github.com/user-attachments/assets/9ffc9c27-adbb-4ef5-8918-ee269f9500c7" width="600" alt="Tab navigation configured in the right sidebar.">

<img src="https://github.com/user-attachments/assets/3394cec0-8bce-4d82-becd-3c52297ec8f8" width="600" alt="Tab navigation configured in the main width sidebar region.">

<img src="https://github.com/user-attachments/assets/9061509b-122c-4c46-a64a-377fde0ec140" width="600" alt="Tab navigation configured in the full width main region.">

Test the following:
* The blocks function as expected based on the above description.
* The blocks scale well at different device viewport widths.
* Views using these blocks pass automated accessibility audits.
* Views using these blocks make sense when using a screen reader.
* The tabs navigation block is keyboard accessible. Users should be able to use arrow keys to navigate between the tabs.

**Comment by katknow** [comment]
I'm getting this error on item pages:
 Error
Call to undefined method Omeka\View\Helper\ResourcePageBlocks::getBlocksArray()

Details:

Error: Call to undefined method Omeka\View\Helper\ResourcePageBlocks::getBlocksArray() in /var/www/html/katknow/OmekaSTesting/themes/Foundation/helper/TabManager.php:17
Stack trace:
#0 /var/www/html/katknow/OmekaSTesting/themes/Foundation/helper/TabManager.php(24): OmekaTheme\Helper\TabManager->getResourcePageBlocks(Object(Omeka\Api\Representation\ItemRepresentation))
#1 /var/www/html/katknow/OmekaSTesting/themes/Foundation/view/omeka/site/item/show.phtml(24): OmekaTheme\Helper\TabManager->getTabNavigationRegion(Object(Omeka\Api\Representation\ItemRepresentation))
#2 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/var/www/html/k...')
#3 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#4 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#5 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#6 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#7 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#8 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#9 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#10 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#11 /var/www/html/katknow/OmekaSTesting/index.php(21): Laminas\Mvc\Application->run()
#12 {main}

**Comment by katknow** [comment]
This is looking good! Scales well and passes accessibility audits. Tabs work well with keyboard. The only thing I'm struggling with is to get the screen reader to consistently get to the blocks to read them. It very well may be user error--I made it happen once with NVDA, but am not sure how.
