### ISSUE TITLE
Test that browse layout selections persist when sorting and paginating

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/foundation#72]
This is the first attempt to address the issue brought up in omeka/omeka-s#2213. When the theme's resource browse layout is set to be toggleable between a grid or list, a user should be able to toggle to a new layout and now have it stick when they use the pagination buttons or sorting form. 

The page remembers the user's setting thanks to a `browse_layout` parameter in the URL. If they navigate to the browse from a non-browse page, it will not remember the user setting.

Test that the browse views remember the user's layout setting. This new functionality is on the `master` branch of the theme.

**Comment by katknow** [comment]
Should the user be able to type a page number into the box and it remember the settings, or just clicking through with pagination? If the latter it seems alright. It does do an interesting thing visually when you click through there where it will briefly flash the other before settling on the correct one.

**Comment by kimisgold** [comment]
I think they should be able to use the pagination text input and have it remember the settings. That it doesn't already is an oversight, so good catch. I'll implement that and let you know when it's ready.

**Comment by kimisgold** [comment]
Okay, the layout setting should work with the page input now and is ready for testing.

**Comment by katknow** [comment]
I think this is now good to go!
