### ISSUE TITLE
Pagination button heights

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/foundation#74]
In Foundation I'm getting different-sized buttons and text between the items browse & the item sets browse, and the items in an item set - I'm assuming you want all this stuff in the row to be the same height:

<img width="809" alt="Screenshot 2024-10-18 at 15 38 49" src="https://github.com/user-attachments/assets/9a02d0ce-f3a1-4b6d-b8a0-ca3fe338c95d">
<img width="807" alt="Screenshot 2024-10-18 at 15 38 58" src="https://github.com/user-attachments/assets/52ade88b-f7ae-4756-9ede-b8d965205979">
<img width="806" alt="Screenshot 2024-10-18 at 15 39 08" src="https://github.com/user-attachments/assets/54e336f3-5de3-4694-ae70-448c9af7ece5">

Linked resources table looks good:
<img width="815" alt="Screenshot 2024-10-18 at 15 42 07" src="https://github.com/user-attachments/assets/7cc9bdbe-c9e7-4082-90cd-fe679f3d5107">

**Comment by kimisgold** [comment]
I did a pass on the pagination controls, among others, in the hopes of getting more consistent looking form elements. Should be ready for a look.

**Comment by allanaaa** [comment]
https://github.com/user-attachments/assets/a71e0bac-4374-4352-a3c5-a6951da7fea5



I'm still seeing a difference between the buttons at the bottom of the items browse, and the buttons at the bottom of the item sets browse. 

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-fourth-site/item

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-fourth-site/item-set

Also, the order on the (top of the) items browse - pagination, Advanced Search, display toggle, sort dropdowns - is not the order on the item sets browse - pagination, display toggle, Advanced Search, no sorting. I think those should be consistent.

Text on the "Sort" button is also very small.

Did you want the sorting stuff to be right-aligned?

**Comment by kimisgold** [comment]
Okay, button order, sizing, sort label size and alignment should all be fixed.

**Comment by allanaaa** [comment]
Looks good!

The grid/list toggle buttons are different colours on the items browse (to show which is already selected) but both are the same colour on the item sets browse. (In Sea Foam at least - will look at the others next.)

I'm also getting horizontal scrolling on a bunch of pages when the browser is below 1215px wide? Map Browse, items browse in list view but not grid view. Not sure which element it's coming from.

**Comment by kimisgold** [comment]
The item set layout toggle buttons were missing a class, which should now be fixed.

With the horizontal scrolling, I'm going to explore that in a separate issue so that it's easier to remember and find.
