### ISSUE TITLE
Horizontal overflow appears on multiple views

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/foundation#75]
From discussion in #74:

> I'm also getting horizontal scrolling on a bunch of pages when the browser is below 1215px wide? Map Browse, items browse in list view but not grid view. Not sure which element it's coming from.

**Comment by kimisgold** [comment]
I saw there was some overflow issues with the search form on map browse when using a vertical menu, and have just applied a fix. I couldn't find the horizontal overflow on item browse with either version of the global menu. If you could provide an example of where you're seeing it, that would help.

**Comment by allanaaa** [comment]
I've just updated to the latest code, today, and now I'm getting big horizontal scroll on the advanced search and map browse pages:

<img width="1233" alt="Screenshot 2024-11-27 at 14 14 59" src="https://github.com/user-attachments/assets/378fc0da-8084-493f-8d56-fc6bc442bc8f">
<img width="1235" alt="Screenshot 2024-11-27 at 14 15 13" src="https://github.com/user-attachments/assets/ac2fd7e7-9f93-4ca0-9cd1-c0a735fb1db0">

That's in Firefox. In Chrome, it's not horizontal-scrolling, but looks like this:

<img width="1317" alt="Screenshot 2024-11-27 at 14 15 39" src="https://github.com/user-attachments/assets/d29f93e8-cb7b-431c-90ad-91cb7c068dba">
<img width="1322" alt="Screenshot 2024-11-27 at 14 15 54" src="https://github.com/user-attachments/assets/b0c142ce-8c1b-4e69-8f77-f2aecd28d5b3">

**Comment by allanaaa** [comment]
... And now I'm seeing the horizontal scroll appear on grid view but not list view on browse pages. This is in both Firefox and Chrome. It's just a tiny tiny bit, like there's some margin bumping out the width. 

<img width="1251" alt="Screenshot 2024-11-27 at 14 27 52" src="https://github.com/user-attachments/assets/f5a3d2d0-3e96-4121-b6aa-cad8b41ab2c2">

**Comment by kimisgold** [comment]
Okay, the fixes are in for the horizontal overflows and ready for a look.

**Comment by allanaaa** [comment]
Thanks!
