### ISSUE TITLE
Timeline colour issue

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/foundation#76]
On a Map block with the Timeline, there is a coloured rectangle showing up near the "Previous" and "Next" arrows that shouldn't be there. Either the background needs to be calculated differently or the background-color should be removed. 

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-fourth-site/page/maps-tests

<img width="917" alt="Screenshot 2024-11-08 at 12 59 51" src="https://github.com/user-attachments/assets/cf450610-face-4c47-b5ff-b5780819c717">

**Comment by kimisgold** [comment]
I've removed overreaching button styles, so buttons with color accents should only apply where specified by the theme or on elements using the `.button` selector.

**Comment by allanaaa** [comment]
This looks good, although you may want to re-style the button that comes with the Output Formats module:

<img width="611" alt="Screenshot 2024-11-18 at 12 55 05" src="https://github.com/user-attachments/assets/70675f91-2693-46d6-acd4-d7877bc38913">

**Comment by kimisgold** [comment]
Okay, styles should be in and ready for testing.

**Comment by allanaaa** [comment]
Looks great, thanks!
